M48
; DRILL file {KiCad 7.0.10} date Thursday, February 15, 2024 at 03:55:14 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-15T15:55:14-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1300
%
G90
G05
T1
X5.278Y-4.758
X6.06Y-2.448
X6.078Y-4.758
X6.61Y-2.998
M30
